#!/bin/bash

VAULT_PATH="/data/data/com.termux/files/home/storage/shared/obsidian-vault"
cd $VAULT_PATH

git add .
git status | grep "nothing to commit" &> /dev/nu
ll
CHANGES=$?

if [ $CHANGES -ne 0 ]; then
    git commit -m "Auto-commit from termux"
fi

git fetch origin

git merge origin/main --no-commit --no-ff

CONFLICTS=$?

echo $CONFLICTS

if [ $CONFLICTS -eq 0 ]; then
    git pull origin main
    git push origin main
else
    git merge --abort

    BRANCH_NAME="conflict-$(date +'%Y%m%d%H%M%S')"
    git checkout -b $BRANCH_NAME
    git push origin $BRANCH_NAME
    termux-notification --title "Git conflict" --content "Conflicts detected. Pushed to $BRANCH_NAME."
fi
